ekf_se:
  frequency: 30.0
  sensor_timeout: 0.1
  two_d_mode: false

  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  odom0: /odom
  odom0_config: [true,  true,  false,
                 false, false, true,
                 false, false, false,
                 false, false, false,
                 false, false, false]
  odom0_differential: false
  odom0_relative: false

  imu0: /imu/filtered  # Subscribe to the FILTERED IMU data!
  imu0_config: [false, false, false,
                true,  true,  true,
                false, false, false,
                true,  true,  true,
                true,  true,  true]
  imu0_differential: true
  imu0_relative: true
  imu0_queue_size: 10

  process_noise_covariance: 0.05
  initial_estimate_covariance: 1e-9
